version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - 1883:1883
      - 9001:9001
  influxdb:
    image: influxdb:alpine
    container_name: influxdb
    volumes:
      - ./etc/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    ports:
      - 8086:8086
  telegraf:
    image: telegraf:alpine
    container_name: telegraf
    network_mode: host
    volumes:
      - ./etc/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
      - mosquitto
  chronograf:
    image: chronograf:alpine
    container_name: chronograf
    ports:
      - 8888:8888
    depends_on:
      - influxdb
